### ISSUE TITLE
Add browser CSS reset

### ISSUE THREAD

**Issue by alexgoff** [GarrettManley/ng-blog#22]
Add a CSS reset for uniform browser styling, normalize.css?

**Comment by alexgoff** [comment]
Going to add this to the initial SASS setup and import normalize.css into the SASS reset file

**Comment by GarrettManley** [comment]
@alexgoff Do we want to pull down https://github.com/HugoGiraudel/sass-boilerplate ???

**Comment by alexgoff** [comment]
https://github.com/matthewelsom/scss-playbook

**Comment by GarrettManley** [comment]
@alexgoff Was this competed with #23 ?

**Comment by alexgoff** [comment]
yes it was
